# Generated by Django 5.0.4 on 2024-04-28 13:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Homes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('maydoni', models.CharField(max_length=200)),
                ('xona_soni', models.IntegerField()),
                ('tamiri', models.CharField(max_length=200)),
                ('sharoitlari', models.CharField(max_length=200)),
                ('yaqin_manzillar', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='homes/images')),
                ('tafsilotlari', models.CharField(max_length=300)),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes_app.category')),
            ],
            options={
                'ordering': ['-publish_time'],
            },
        ),
    ]
