# Generated by Django 5.0.4 on 2024-04-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homes',
            name='narxi',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
