# Generated by Django 5.0.4 on 2024-04-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes_app', '0002_homes_narxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='homes',
            name='manzil',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
