# Generated by Django 5.0.4 on 2024-05-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes_app', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='publish_time',
        ),
    ]
