# Generated by Django 5.0.4 on 2024-05-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes_app', '0006_tariff_homes_larifi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homes',
            old_name='larifi',
            new_name='tarifi',
        ),
    ]
