# Generated by Django 5.0.4 on 2024-05-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes_app', '0007_rename_larifi_homes_tarifi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homes',
            name='tarifi',
            field=models.CharField(blank=True, choices=[('maxsus', 'Maxsus'), ('oddiy', 'Oddiy')], default='oddiy', max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='Tariff',
        ),
    ]
