# Generated by Django 5.0.4 on 2024-05-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes_app', '0008_alter_homes_tarifi_delete_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='homes',
            name='tel',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
