# Generated by Django 5.0.4 on 2024-05-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes_app', '0009_homes_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homes',
            name='tarifi',
            field=models.CharField(blank=True, choices=[('maxsus', 'Maxsus'), ("o'rta", 'Orta'), ('oddiy', 'Oddiy')], default='oddiy', max_length=6, null=True),
        ),
    ]
