# Generated by Django 5.0.6 on 2024-05-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes_app', '0012_category_name_en_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homes',
            name='sharoitlari',
        ),
        migrations.RemoveField(
            model_name='homes',
            name='yaqin_manzillar',
        ),
        migrations.AlterField(
            model_name='homes',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
